### ISSUE TITLE
Question about SL calculation

### ISSUE THREAD

**Issue by scramjetFoam** [ZSHtju/reactingDNS_OpenFOAM#11]
Hello,

I am currently comparing the results of reactingDNS with the differential diffusion implemented in the openfoam-dev version and the calculations from Cantera. I have a question. How is the laminar flame speed (SL) calculated in OpenFOAM (SLComparisonWithCantera.pdf)? Thank you.

BR,
Shang

**Comment by ZSHtju** [comment]
> Hello,
> 
> I am currently comparing the results of reactingDNS with the differential diffusion implemented in the openfoam-dev version and the calculations from Cantera. I have a question. How is the laminar flame speed (SL) calculated in OpenFOAM (SLComparisonWithCantera.pdf)? Thank you.
> 
> BR, Shang

Hi Shang,
One-dimensional permixed flame (https://github.com/ZSHtju/reactingDNS_OpenFOAM/tree/OpenFOAM8/tuts/1D_H2_premixed_inletoutlet) is performed in OpenFOAM to calculate the laminar flame speed (SL), and the initial profile is adapted from the Cantera results using (https://github.com/ZSHtju/1DFlameSin2Foam), the inlet velocity (U0) is set to the SL from Cantera. After the flame reaches a quasi-steady state, the SL is computed using the movement of the flame front (defined by the maximum temperature gradient), e.g. from x0 to x1, in a time interval from t0 to t1.  SL_reactingDNS = U0 - (x1-x0)/(t1-t0) 
BR, Shenghui

**Comment by scramjetFoam** [comment]
> > Hello,
> > I am currently comparing the results of reactingDNS with the differential diffusion implemented in the openfoam-dev version and the calculations from Cantera. I have a question. How is the laminar flame speed (SL) calculated in OpenFOAM (SLComparisonWithCantera.pdf)? Thank you.
> > BR, Shang
> 
> Hi Shang, One-dimensional permixed flame (https://github.com/ZSHtju/reactingDNS_OpenFOAM/tree/OpenFOAM8/tuts/1D_H2_premixed_inletoutlet) is performed in OpenFOAM to calculate the laminar flame speed (SL), and the initial profile is adapted from the Cantera results using (https://github.com/ZSHtju/1DFlameSin2Foam), the inlet velocity (U0) is set to the SL from Cantera. After the flame reaches a quasi-steady state, the SL is computed using the movement of the flame front (defined by the maximum temperature gradient), e.g. from x0 to x1, in a time interval from t0 to t1. SL_reactingDNS = U0 - (x1-x0)/(t1-t0) BR, Shenghui

Roger it. Thanks.
