### ISSUE TITLE
Compiling errors on OF2206

### ISSUE THREAD

**Issue by manaman8** [ZSHtju/reactingDNS_OpenFOAM#5]
Thanks for making reactingDNS available! 

I am trying to compile reactingDNS on OFv2206. I copied the `solvers/reactingDNS` to `"$WM_PROJECT_DIR"/applications/solvers/combustion/` and then tried compiling using `./Allwmake`.

I am getting the below erros 

```
Making dependency list for source file reactingDNS.C
wmkdepend: could not open 'fluidThermoMomentumTransportModel.H' for source file 'reactingDNS.C': No such file or directory
wmkdepend: could not open 'psiReactionThermophysicalTransportModel.H' for source file 'reactingDNS.C': No such file or directory
wmkdepend: could not open 'compressibleTransportModel.H' for source file 'reactingDNS.C': No such file or directory
wmkdepend: could not open 'turbulentFluidThermoModel.H' for source file 'reactingDNS.C': No such file or directory
wmkdepend: parse error while scanning 'createFields.H' ... perhaps missing a final newline
wmkdepend: parse error while scanning 'readChemistryProperties.H' ... perhaps missing a final newline
```
Am I doing something wrong?

Mana

**Comment by manaman8** [comment]
Retried compiling on OFv9. Same errors.

**Comment by ZSHtju** [comment]
Unfortunately, current available version on the Github is only for OpenFOAM 8 (https://openfoam.org/release/8/).
You can either turn to OpenFOAM 8 or wait me to update the code to latest version like OpenFOAM 10 and OpenFOAMv2206.

**Comment by manaman8** [comment]
Took me a while to figure out it was a version compatibility issue! Thank you for the reply. I am trying to couple your TCI model with LES to model a hydrogen jet diffusion flame. Will be in touch about how that goes! Mana

**Comment by ZSHtju** [comment]
Hi Mana,
Thanks for your email.
Unfortunately, current available version on the Github is only for OpenFOAM 8 (https://openfoam.org/release/8/).
Several days ago, another research sent me a email for the same issue as you have.
You can either turn to OpenFOAM 8 or wait me to update the code to latest version like OpenFOAM 10 and OpenFOAMv2206.
BR/Shenghui


&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Aug 16, 2022 12:37 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[ZSHtju/reactingDNS_OpenFOAM] Compiling errors on OF2206 (Issue #5)

&nbsp;



 
Thanks for making reactingDNS available!
 
I am trying to compile reactingDNS on OFv2206. I copied the solvers/reactingDNS to "$WM_PROJECT_DIR"/applications/solvers/combustion/ and then tried compiling using ./Allwmake.
 
I am getting the below erros
 Making dependency list for source file reactingDNS.C wmkdepend: could not open 'fluidThermoMomentumTransportModel.H' for source file 'reactingDNS.C': No such file or directory wmkdepend: could not open 'psiReactionThermophysicalTransportModel.H' for source file 'reactingDNS.C': No such file or directory wmkdepend: could not open 'compressibleTransportModel.H' for source file 'reactingDNS.C': No such file or directory wmkdepend: could not open 'turbulentFluidThermoModel.H' for source file 'reactingDNS.C': No such file or directory wmkdepend: parse error while scanning 'createFields.H' ... perhaps missing a final newline wmkdepend: parse error while scanning 'readChemistryProperties.H' ... perhaps missing a final newline  
Am I doing something wrong?
 
Mana

**Comment by drhcelik** [comment]
I have working OF-10 version; even though it may need several additional tests. I may merge it with your repo if you like.

**Comment by ZSHtju** [comment]
> I have working OF-10 version; even though it may need several additional tests. I may merge it with your repo if you like.

Sure, that will be great. Please send it to me or make a pull request.
