### ISSUE TITLE
Eq. 2-14 needs a modification in the pdf document.

### ISSUE THREAD

**Issue by Parsa-Aalto** [ZSHtju/reactingDNS_OpenFOAM#7]
Hello, 
Please check Eq. (2-14) in the document:
(Mu_k/Mu_L)**0.5 + (M_k/M_L)**0.25 should be  (Mu_k/Mu_L)**0.5 * (M_k/M_L)**0.25. 
I think (+) should be replaced by (*).

Thank you so much.
Regards,
Parsa

**Comment by ZSHtju** [comment]
> Hello, Please check Eq. (2-14) in the document: (Mu_k/Mu_L)**0.5 + (M_k/M_L)**0.25 should be (Mu_k/Mu_L)**0.5 * (M_k/M_L)**0.25. I think (+) should be replaced by (*).
> 
> Thank you so much. Regards, Parsa

Hi,
I have checked this equation. You are right. The (+) should be replaced by (*).
The document will be updated soon.
Thanks.
