### ISSUE TITLE
Eq. (2.6) -> Please re-check it in the document.

### ISSUE THREAD

**Issue by Parsa-Aalto** [ZSHtju/reactingDNS_OpenFOAM#8]
Hello Shenghui,

I would really appreciate it if you could kindly check the sign for Eq. (2.6). 
I have checked it with different sources and I believe that a (-) sign should be inserted before D_km. 

Thank you so much.

Regards,
Parsa

**Comment by ZSHtju** [comment]
Thanks a lot for the detail review.
I will take a look and come back to you later.

BR/Shenghui

**Comment by drhcelik** [comment]
As a comment, Eq. (7) from Premix User Guide could be helpful.

[Premixed User Guide](http://www.cvd.louisville.edu/Course/Chemical%20Vapour%20Deposition/Manuals/chemkin/chemkin7premix.pdf)

**Comment by ZSHtju** [comment]
Thanks again, the document has been updated.

**Comment by Parsa-Aalto** [comment]
Thank you.
